name: Install dependencies
description: Install dependencies using yarn and enable caching
author: 'Technology Studio'
inputs:
  use-cache:
    description: Whether to use the cache
    required: false
    default: 'true'
outputs:
  download-cache-dir:
    description: The yarn cache directory
    value: ${{ steps.yarn-cache-dir.outputs.dir }}
  download-cache-primary-key:
    description: The cache key used for restoring the yarn cache
    value: ${{ steps.cache-restore-yarn.outputs.cache-primary-key }}
  node-modules-primary-key:
    description: The cache key used for restoring the node modules
    value: ${{ steps.cache-restore-node-modules.outputs.cache-primary-key }}
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
      with:
        node-version-file: '.nvmrc'
    - run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      shell: bash
      id: yarn-cache-dir
    - uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      if: inputs.use-cache == 'true'
      id: cache-restore-yarn
      with:
        path: ${{ steps.yarn-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      if: inputs.use-cache == 'true'
      id: cache-restore-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-
    - run: yarn install --frozen-lockfile
      shell: bash
