name: Install dependencies
description: Install dependencies using yarn and enable caching
author: 'Technology Studio'
outputs:
  cache-dir:
    description: The yarn cache directory
    value: ${{ steps.yarn-cache-dir.outputs.dir }}
  cache-primary-key:
    description: The cache key used for restoring the yarn cache
    value: ${{ steps.cache-restore-yarn.outputs.cache-primary-key }}
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
      with:
        node-version-file: '.nvmrc'
    - run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      shell: bash
      id: yarn-cache-dir
    - uses: actions/cache/restore@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4
      id: cache-restore-yarn
      with:
        path: ${{ steps.yarn-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: yarn install --frozen-lockfile
      shell: bash
