name: Send a Slack message on failed job
description: Send a Slack message when a job fails
author: 'Technology Studio'
runs:
  using: 'composite'
  steps:
    - name: 'Post a message'
      id: slack
      uses: slackapi/slack-github-action@v1.25.0
      # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
      channel-id: 'C06KCA4KEC9'
      # For posting a simple plain text message
      slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
env:
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
