name: 'Send Slack Notification'
description: 'Sends a message to Slack on job failure'
inputs:
  slack_bot_token:
    description: 'Slack bot token'
    required: true
  channel_id:
    description: 'Slack channel ID'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Post a message to Slack
      uses: slackapi/slack-github-action@6c661ce58804a1a20f6dc5fbee7f0381b469e001 # v1.25.0
      with:
        channel-id: ${{ inputs.channel_id }}
        slack-message: 'Pull request check failed: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}'
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack_bot_token }}
