name: 'Send Slack Notification'
description: 'Sends a message to Slack on job failure'
inputs:
  slack_bot_token:
    description: 'Slack bot token'
    required: true
  channel_id:
    description: 'Slack channel ID'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Prepare Slack Message
      shell: bash
      run: |
        {
          echo "SLACK_MESSAGE<<EOF"
          echo "\`${{ github.repository }}\` Workflow <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}> failed"

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "PR <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}>"
          elif [[ "${{ github.event_name }}" == "schedule" ]]; then
            echo "Scheduled workflow"
            echo "Cron: ${{ github.event.schedule }}"
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            echo "Branch: \`${{ github.ref_name }}\`"
            echo "Commit: <${{ github.event.head_commit.url }}|${{ github.event.head_commit.message }}>"
          else
            echo "Workflow details:"
            echo "- Ref: ${{ github.ref }}"
            echo "- SHA: ${{ github.sha }}"
          fi

          echo EOF
        } >> $GITHUB_ENV

    - name: Post a message to Slack
      uses: slackapi/slack-github-action@37ebaef184d7626c5f204ab8d3baff4262dd30f0 # v1.27.0
      with:
        channel-id: ${{ inputs.channel_id }}
        slack-message: ${{ env.SLACK_MESSAGE }}
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack_bot_token }}
