name: 'Send Slack Notification'
description: 'Sends a message to Slack on job failure'
inputs:
  slack_bot_token:
    description: 'Slack bot token'
    required: true
  channel_id:
    description: 'Slack channel ID'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Prepare Slack Message
      shell: bash
      run: |
        {
          echo "SLACK_MESSAGE<<EOF"
          echo "\`${{ github.repository }}\` Workflow <${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}> failed"
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "PR <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}>"
            echo EOF
          else
            echo "Branch \`${{ github.ref_name }}\` - <${{ github.event.head_commit.url }}|${{ github.event.head_commit.message }}>"
            echo EOF
          fi
        } >> $GITHUB_ENV

    - name: Post a message to Slack
      uses: slackapi/slack-github-action@70cd7be8e40a46e8b0eced40b0de447bdb42f68e # v1.26.0
      with:
        channel-id: ${{ inputs.channel_id }}
        slack-message: ${{ env.SLACK_MESSAGE }}
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack_bot_token }}
