name: 'Send Slack Notification'
description: 'Sends a message to Slack on job failure'
inputs:
  slack_bot_token:
    description: 'Slack bot token'
    required: true
  channel_id:
    description: 'Slack channel ID'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Prepare Slack Message
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        {
          COMMIT_MESSAGE=$(gh api repos/${{ github.repository }}/commits/${{ github.sha }} --jq '.commit.message')
          echo "SLACK_MESSAGE<<EOF"
          echo "\`${{ github.repository }}\` Workflow <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}> failed"

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "PR <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}>"
          elif [[ "${{ github.event_name }}" == "schedule" ]]; then
            echo "Scheduled workflow"
            echo "Branch: \`${{ github.ref_name }}\` - SHA: \`${{ github.sha }}\`"
            echo "Commit message: \`${COMMIT_MESSAGE}\`"
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            echo "Branch: \`${{ github.ref_name }}\`"
            echo "Commit: <${{ github.event.head_commit.url }}|${{ github.event.head_commit.message }}>"
          else
            echo "Branch: \`${{ github.ref_name }}\`"
            echo "SHA: \`${{ github.sha }}\`"
            echo "Commit message: \`${COMMIT_MESSAGE}\`"
          fi

          echo EOF
        } >> $GITHUB_ENV

    - name: Post a message to Slack
      uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # v2.0.0
      with:
        method: chat.postMessage
        token: ${{ inputs.slack_bot_token }}
        payload: |
          channel: ${{ inputs.channel_id }}
          text: ${{ env.SLACK_MESSAGE }}
