name: Save dependencies
description: Save installed dependencies to cache
author: 'Technology Studio'
inputs:
  download-cache-dir:
    description: The yarn/bun cache directory
  download-cache-primary-key:
    description: The cache key used for storing the yarn/bun cache
  node-modules-primary-key:
    description: The cache key used for restoring the node modules
  cache_mode:
    description: The cache mode
runs:
  using: 'composite'
  steps:
    - name: Remove node_modules for download cache mode
      if: inputs.cache_mode == 'download'
      run: rm -rf node_modules && mkdir node_modules
      shell: bash
    - name: Save dependencies
      uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: ${{ inputs.download-cache-dir }}
        key: ${{ inputs.download-cache-primary-key }}
    - uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: |
          node_modules
        key: ${{ inputs.node-modules-primary-key }}
