name: Save dependencies
description: Save installed dependencies to cache
author: 'Technology Studio'
inputs:
  download-cache-dir:
    description: The yarn cache directory
  download-cache-primary-key:
    description: The cache key used for storing the yarn cache
  node-modules-primary-key:
    description: The cache key used for restoring the node modules
runs:
  using: 'composite'
  steps:
    - name: Save dependencies
      uses: actions/cache/save@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4
      with:
        path: ${{ inputs.download-cache-dir }}
        key: ${{ inputs.download-cache-primary-key }}
    - uses: actions/cache/save@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4
      with:
        path: |
          node_modules
        key: ${{ inputs.node-modules-primary-key }}
