name: Save dependencies
description: Save installed dependencies to cache
author: 'Technology Studio'
inputs:
  cache-dir:
    description: The yarn cache directory
  cache-primary-key:
    description: The cache key used for storing the yarn cache
runs:
  using: 'composite'
  steps:
    - uses: actions/cache/save@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
      with:
        path: ${{ inputs.cache-dir }}
        key: ${{ inputs.cache-primary-key }}
