name: "Branch Head Commit Status Check"

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      check-status-context-pattern:
        required: true
        description: Regex pattern of the check status context name
        type: string
      pr-number:
        required: true
        type: number
    
permissions:
  issues: read
  pull-requests: read
  statuses: read

jobs:
  main:
    name: Check head commit status
    runs-on: ubuntu-latest
    outputs:
      hotfix: ${{ steps.pr_labels.outputs.hotfix }}
    steps:
      - name: Fetch PR labels
        id: pr_labels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LABELS=$(curl -s \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ inputs.pr-number }}/labels" | jq -r '.[] | .name') 
          echo "PR Labels: $LABELS"

          # Check if 'hotfix' label is present and write to file
          if echo "$LABELS" | grep -q 'hotfix'; then
            echo "hotfix=true" >> $GITHUB_OUTPUT
          else
            echo "hotfix=false" >> $GITHUB_OUTPUT
          fi

      - name: Fetch status of head commit on ${{ inputs.branch }}
        if: steps.pr_labels.outputs.hotfix != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CONTEXT="ci/trunk-health"

          STATUSES=$(curl -s \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/commits/${{ inputs.branch }}/statuses")
          FILTERED_STATUSES=$(echo "$STATUSES" | jq -r '.[] | select(.context | test("${{ inputs.check-status-context-pattern }}")) | .state')
          
          PR_HEAD_SHA=$(curl -s \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ inputs.pr-number }}" | jq -r '.head.sha')

          create_status() {
            curl -s \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              -X POST \
              "https://api.github.com/repos/${{ github.repository }}/statuses/${PR_HEAD_SHA}" \
              -d "{\"state\": \"$1\", \"context\": \"${CONTEXT}\", \"description\": \"$2\", \"target_url\": \"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}"
          }

          # Check if any filtered status is success
          if echo "$FILTERED_STATUSES" | grep -q "success"; then
            create_status success "Branch head commit status check succeeded"
          else
            create_status failure "Branch head commit status check failed"
          fi
