name: 'Code style'

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: technology-studio/github-workflows/.github/actions/install-dependencies@main
      - run: yarn lint
