name: 'Code quality'

on:
  workflow_call:

jobs:
  lint:
    name: "/"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: technology-studio/github-workflows/.github/actions/install-dependencies@main
      - name: Get PR title
        id: get-pr-title
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR_TITLE=$(gh pr view ${{ github.event.pull_request.number }} --json title --jq '.title')
          echo "pr_title=$PR_TITLE" >> $GITHUB_ENV
          echo "PR Title: $PR_TITLE"
      - if: "!contains(steps.get-pr-title.outputs.pr_title, 'test1')"
        run: yarn lint:ci
      - name: Check if pr contains test1
        if: contains(steps.get-pr-title.outputs.pr_title, 'test1')
        run: |
          echo "pr contains test1"
          yarn txo-eslint ver --cache
      - name: Send a Slack message on failure
        if: failure()
        uses: technology-studio/github-workflows/.github/actions/slack-failed-job-message@main
        with:
          slack_bot_token: ${{ secrets.TXO_SLACK_BOT_APP_TOKEN }}
          channel_id: ${{ secrets.TXO_SLACK_GITHUB_OPS_CHANNEL_ID }}
