name: 'Code quality'

on:
  workflow_call:

jobs:
  lint:
    name: "/"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: technology-studio/github-workflows/.github/actions/install-dependencies@main
      - if: "!contains(github.event.pull_request.title, 'update dependency eslint-config-txo')"
        run: yarn lint:ci
      - name: Validate ESLint run if PR title contains `update dependency eslint-config-txo`
        if: contains(github.event.pull_request.title, 'update dependency eslint-config-txo')
        run: yarn txo-eslint ver --cache
      - name: Send a Slack message on failure
        if: failure()
        uses: technology-studio/github-workflows/.github/actions/slack-failed-job-message@main
        with:
          slack_bot_token: ${{ secrets.TXO_SLACK_BOT_APP_TOKEN }}
          channel_id: ${{ secrets.TXO_SLACK_GITHUB_OPS_CHANNEL_ID }}
