name: Update eslint CI rules

on:
  workflow_call:
    inputs:
      cache_mode:
        type: string
        default: download

jobs:
  update-eslint-ci-rules:
    name: "/"
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: technology-studio/github-workflows/.github/actions/install-dependencies@331e6f866da04053d27ba5890d1b9c60bc8ed2fa # main
        id: install
        with:
          use-cache: false
      - name: Update eslint-ci-rules if needed (yarn)
        run: |
          if ! yarn lint:ci; then
            echo "Linting failed. Updating eslint-ci-rules.json..."
            yarn txo-eslint update-ci-rules
            changed_files=$(git diff --name-only)
            if [[ "$changed_files" == "eslint-ci-rules.json" ]]; then
              git config --global user.email "txo-github-bot[bot]@users.noreply.github.com"
              git config --global user.name "TXO GitHub Bot[bot]"
              git add eslint-ci-rules.json
              git commit -m "chore: update eslint-ci-rules.json [skip ci]"
              git push
            fi
          else
            echo "Linting passed. No update needed."
          fi
      - name: Update eslint-ci-rules if needed (bun)
        run: |
          if ! bun run --bun lint:ci; then
            echo "Linting failed. Updating eslint-ci-rules.json..."
            bun run --bun txo-eslint update-ci-rules
            changed_files=$(git diff --name-only)
            if [[ "$changed_files" == "eslint-ci-rules.json" ]]; then
              git config --global user.email "txo-github-bot[bot]@users.noreply.github.com"
              git config --global user.name "TXO GitHub Bot[bot]"
              git add eslint-ci-rules.json
              git commit -m "chore: update eslint-ci-rules.json [skip ci]"
              git push
            fi
          else
            echo "Linting passed. No update needed."
          fi
