name: 'Install dependencies and generate yarn cache'

on:
  workflow_call:
    inputs:
      commit_ref:
        type: string
        required: true

jobs:
  install-dependencies-and-generate-yarn-cache:
    name: '/'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout specific commit
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          ref: ${{ inputs.commit_ref }}
      - name: Install app dependencies
        uses: technology-studio/github-workflows/.github/actions/install-app-dependencies@main
        id: install
      - name: Save app dependencies
        uses: technology-studio/github-workflows/.github/actions/save-app-dependencies@main
        with:
          download-cache-dir: ${{ steps.install.outputs.download-cache-dir }}
          download-cache-primary-key: ${{ steps.install.outputs.download-cache-primary-key }}
          node-modules-primary-key: ${{ steps.install.outputs.node-modules-primary-key }}
