name: "Install dependencies and generate yarn cache"

on:
  workflow_call:
    inputs:
      commit_ref:
        type: string
        required: true

jobs:
  install-dependencies-and-generate-yarn-cache:
    name: "/"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout specific commit
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          ref: ${{ inputs.commit_ref }}
      - name: Check if commit has succeessful checks
        uses: actions/github-script@35b1cdd1b2c1fc704b1cd9758d10f67e833fcb02
        permissions:
          contents: read
        id: check-commit-checks
        with:
          result-encoding: string
          script: |
            const commitStatuses = await github.paginate(github.rest.repos.listCommitStatusesForRef, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "${{ inputs.commit_ref }}",
              per_page: 100
            })
            const isHealthy = (platform) => {
              const platformCommitStatuses = commitStatuses.filter(status => (status.context === `Build health / ${platform}`))
              if (platformCommitStatuses.length > 0 && platformCommitStatuses[0].state === 'success') {
                return true;
              }
              return false;
            }
            if (isHealthy('iOS') && isHealthy('Android')) {
              return true
            }
            return false
      - name: Install app dependencies
        if: steps.check-commit-checks.outputs.result == 'true'
        uses: technology-studio/github-workflows/.github/actions/install-app-dependencies@esl/generate-yarn-cache
        id: install
      - name: Save app dependencies
        if: steps.check-commit-checks.outputs.result == 'true'
        uses: technology-studio/github-workflows/.github/actions/save-app-dependencies@esl/generate-yarn-cache
        with:
          download-cache-dir: ${{ steps.install.outputs.download-cache-dir }}
          download-cache-primary-key: ${{ steps.install.outputs.download-cache-primary-key }}
          node-modules-primary-key: ${{ steps.install.outputs.node-modules-primary-key }}
