name: "PR"

on:
  workflow_call:

jobs:
  main:
    name: Ensure semantic PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@e9fabac35e210fea40ca5b14c0da95a099eff26f # v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
