name: 'Prisma'

on:
  workflow_call:

jobs:
  prisma-schema:
    name: "/"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: technology-studio/github-workflows/.github/actions/install-dependencies@main
        id: install
      - run: yarn schema:process
      - name: Check not processed schema
        run: |
          git diff
          exit $(git status --porcelain=v1 2>/dev/null|wc -l)
      - name: Send a Slack message on failure
        if: failure()
        uses: technology-studio/github-workflows/.github/actions/slack-failed-job-message@main
        with:
          slack_bot_token: ${{ secrets.TXO_SLACK_BOT_APP_TOKEN }}
          channel_id: ${{ secrets.TXO_SLACK_GITHUB_OPS_CHANNEL_ID }}
