name: Release

on:
  workflow_call:
    secrets:
      SEMANTIC_RELEASE_SLACK_WEBHOOK:
        required: true
      NPM_TOKEN:
        required: true
      TXO_GITHUB_BOT_APP_ID:
        required: true
      TXO_GITHUB_BOT_APP_PRIVATE_KEY:
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/github-app-token-generator@b96ff604b2300989cd1105e3fad09199fca56681 # v1
        id: get-token
        with:
          app-id: ${{ secrets.TXO_GITHUB_BOT_APP_ID }}
          private-key: ${{ secrets.TXO_GITHUB_BOT_APP_PRIVATE_KEY }}
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: technology-studio/github-workflows/.github/actions/install-dependencies@main
        id: install
      - run: yarn test --coverage
      - uses: codecov/codecov-action@125fc84a9a348dbcf27191600683ec096ec9021c # v4
      - run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SEMANTIC_RELEASE_SLACK_WEBHOOK }}
      - uses: technology-studio/github-workflows/.github/actions/save-dependencies@main
        with:
          cache-dir: ${{ steps.install.outputs.cache-dir }}
          cache-primary-key: ${{ steps.install.outputs.cache-primary-key }}
      - name: Send a Slack message on failure
        if: failure()
        uses: technology-studio/github-workflows/.github/actions/slack-failed-job-message@main
        with:
          slack_bot_token: ${{ secrets.TXO_SLACK_BOT_APP_TOKEN }}
          channel_id: ${{ secrets.TXO_SLACK_GITHUB_OPS_CHANNEL_ID }} 
