name: Release

on:
  workflow_call:
    inputs:
      cache_mode:
        type: string
        default: download
    secrets:
      SEMANTIC_RELEASE_SLACK_WEBHOOK:
        required: true
      TXO_SLACK_BOT_APP_TOKEN:
        required: true
      TXO_SLACK_GITHUB_OPS_CHANNEL_ID:
        required: true

permissions:
  id-token: write
  contents: write

jobs:
  release:
    name: "/"
    runs-on: ubuntu-latest
    environment: default-branch-semantic-release
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: technology-studio/github-workflows/.github/actions/install-dependencies-bun@main
        id: install
        with:
          use-cache: false
      - run: bun run test --coverage
      - name: Check if coverage was generated
        id: check-coverage
        run: |
          if [[ -d "coverage" ]]; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi
      - if: steps.check-coverage.outputs.exists == 'true'
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
      - run: bun run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SEMANTIC_RELEASE_SLACK_WEBHOOK }}
      - uses: technology-studio/github-workflows/.github/actions/save-dependencies@main
        with:
          cache_mode: ${{ inputs.cache_mode }}
          download-cache-dir: ${{ steps.install.outputs.download-cache-dir }}
          download-cache-primary-key: ${{ steps.install.outputs.download-cache-primary-key }}
          node-modules-primary-key: ${{ steps.install.outputs.node-modules-primary-key }}
      - name: Send a Slack message on failure
        if: failure()
        uses: technology-studio/github-workflows/.github/actions/slack-failed-job-message@main
        with:
          slack_bot_token: ${{ secrets.TXO_SLACK_BOT_APP_TOKEN }}
          channel_id: ${{ secrets.TXO_SLACK_GITHUB_OPS_CHANNEL_ID }}
