name: Release

on:
  workflow_call:
    inputs:
      cache_mode:
        type: string
        default: download
    secrets:
      SEMANTIC_RELEASE_SLACK_WEBHOOK:
        required: true
      TXO_SLACK_BOT_APP_TOKEN:
        required: true
      TXO_SLACK_GITHUB_OPS_CHANNEL_ID:
        required: true

permissions:
  id-token: write
  contents: write

jobs:
  release:
    name: "/"
    runs-on: ubuntu-latest
    environment: default-branch-semantic-release
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: technology-studio/github-workflows/.github/actions/install-dependencies@main
        id: install
        with:
          use-cache: false
      - run: yarn test --coverage
      - id: codecov
        continue-on-error: true
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          fail_ci_if_error: true
          use_oidc: true
      - name: Send a Slack message on codecov failure
        if: steps.codecov.outcome == 'failure'
        uses: technology-studio/github-workflows/.github/actions/slack-failed-job-message@main
        with:
          slack_bot_token: ${{ secrets.TXO_SLACK_BOT_APP_TOKEN }}
          channel_id: ${{ secrets.TXO_SLACK_GITHUB_OPS_CHANNEL_ID }}
          status_text: '🟠 codecov upload failed (job continued)'
      - run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SEMANTIC_RELEASE_SLACK_WEBHOOK }}
      - uses: technology-studio/github-workflows/.github/actions/save-dependencies@main
        with:
          cache_mode: ${{ inputs.cache_mode }}
          download-cache-dir: ${{ steps.install.outputs.download-cache-dir }}
          download-cache-primary-key: ${{ steps.install.outputs.download-cache-primary-key }}
          node-modules-primary-key: ${{ steps.install.outputs.node-modules-primary-key }}
      - name: Send a Slack message on failure
        if: failure()
        uses: technology-studio/github-workflows/.github/actions/slack-failed-job-message@main
        with:
          slack_bot_token: ${{ secrets.TXO_SLACK_BOT_APP_TOKEN }}
          channel_id: ${{ secrets.TXO_SLACK_GITHUB_OPS_CHANNEL_ID }}
