name: Release

on:
  workflow_call:
    inputs:
      cache_mode:
        type: string
        default: download
    secrets:
      SEMANTIC_RELEASE_SLACK_WEBHOOK:
        required: true
      NPM_TOKEN:
        required: true
      TXO_GITHUB_BOT_APP_ID:
        required: true
      TXO_GITHUB_BOT_APP_PRIVATE_KEY:
        required: true

jobs:
  release:
    name: "/"
    runs-on: ubuntu-latest
    environment: default-branch-semantic-release
    steps:
      - uses: technology-studio/github-workflows/.github/actions/github-app-token-generator@main
        id: get-token
        with:
          app-id: ${{ secrets.TXO_GITHUB_BOT_APP_ID }}
          private-key: ${{ secrets.TXO_GITHUB_BOT_APP_PRIVATE_KEY }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: technology-studio/github-workflows/.github/actions/install-dependencies@main
        id: install
      - run: yarn test --coverage
      - uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4
      - run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SEMANTIC_RELEASE_SLACK_WEBHOOK }}
      - name: Remove node_modules for download cache mode
        if: inputs.cache_mode == 'download'
        run: rm -rf node_modules && mkdir node_modules
      - uses: technology-studio/github-workflows/.github/actions/save-dependencies@main
        with:
          download-cache-dir: ${{ steps.install.outputs.download-cache-dir }}
          download-cache-primary-key: ${{ steps.install.outputs.download-cache-primary-key }}
          node-modules-primary-key: ${{ steps.install.outputs.node-modules-primary-key }}
      - name: Send a Slack message on failure
        if: failure()
        uses: technology-studio/github-workflows/.github/actions/slack-failed-job-message@main
        with:
          slack_bot_token: ${{ secrets.TXO_SLACK_BOT_APP_TOKEN }}
          channel_id: ${{ secrets.TXO_SLACK_GITHUB_OPS_CHANNEL_ID }}
