name: Release

on:
  workflow_call:
    secrets:
      SEMANTIC_RELEASE_SLACK_WEBHOOK:
        required: true
      NPM_TOKEN:
        required: true
      TXO_GITHUB_BOT_APP_ID:
        required: true
      TXO_GITHUB_BOT_APP_PRIVATE_KEY:
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/github-app-token-generator@a3831f44404199df32d8f39f7c0ad9bb8fa18b1c # v1
        id: get-token
        with:
          app-id: ${{ secrets.TXO_GITHUB_BOT_APP_ID }}
          private-key: ${{ secrets.TXO_GITHUB_BOT_APP_PRIVATE_KEY }}
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: technology-studio/github-workflows/.github/actions/install-dependencies@main
        id: install
      - run: yarn test --coverage
      - uses: codecov/codecov-action@4fe8c5f003fae66aa5ebb77cfd3e7bfbbda0b6b0 # v3
      - run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SEMANTIC_RELEASE_SLACK_WEBHOOK }}
      - uses: technology-studio/github-workflows/.github/actions/save-dependencies@main
        with:
          cache-dir: ${{ steps.install.outputs.cache-dir }}
          cache-primary-key: ${{ steps.install.outputs.cache-primary-key }}
