name: Release
on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: technology-studio/github-workflows/.github/actions/install-dependencies@main
        id: install
      - run: yarn test --coverage
      - uses: codecov/codecov-action@v3
      - run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELASE_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SEMANTIC_RELEASE_SLACK_WEBHOOK }}
      - uses: technology-studio/github-workflows/.github/actions/save-dependencies@main
        with:
          cache-dir: ${{ steps.install.outputs.cache-dir }}
          cache-primary-key: ${{ steps.install.outputs.cache-primary-key }}
