name: Embed code in README

on:
  workflow_call:
    secrets:
      TXO_GITHUB_BOT_APP_ID:
        required: true
      TXO_GITHUB_BOT_APP_PRIVATE_KEY:
        required: true

jobs:
  embed-code:
    name: "/"
    runs-on: ubuntu-latest
    environment: default-branch-readme-sync
    steps:
      - uses: technology-studio/github-workflows/.github/actions/github-app-token-generator@main
        id: get-token
        with:
          app-id: ${{ secrets.TXO_GITHUB_BOT_APP_ID }}
          private-key: ${{ secrets.TXO_GITHUB_BOT_APP_PRIVATE_KEY }}
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: technology-studio-forks/markdown-embed-code@b7279b286dbbcaa341fdacf261854ede2c4ab756 # v1.1.4
        with:
          markdown: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "docs: synchronizing README.md"
          silent: true
