name: Embed code in README

on:
  workflow_call:
    secrets:
      SEMANTIC_RELEASE_APP_ID:
        required: true
      SEMANTIC_RELEASE_APP_PRIVATE_KEY:
        required: true

jobs:
  embed-code:
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          app-id: ${{ secrets.SEMANTIC_RELEASE_APP_ID }}
          private-key: ${{ secrets.SEMANTIC_RELEASE_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: technology-studio-forks/markdown-embed-code@b7279b286dbbcaa341fdacf261854ede2c4ab756 # v1.1.4
        with:
          markdown: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "docs: synchronizing README.md"
          silent: true
