name: Embed code in README

on:
  workflow_call:
    secrets:
      TXO_GITHUB_BOT_APP_ID:
        required: true
      TXO_GITHUB_BOT_APP_PRIVATE_KEY:
        required: true

jobs:
  embed-code:
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/github-app-token-generator@a3831f44404199df32d8f39f7c0ad9bb8fa18b1c # v1
        id: get-token
        with:
          app-id: ${{ secrets.TXO_GITHUB_BOT_APP_ID }}
          private-key: ${{ secrets.TXO_GITHUB_BOT_APP_PRIVATE_KEY }}
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: technology-studio-forks/markdown-embed-code@b7279b286dbbcaa341fdacf261854ede2c4ab756 # v1.1.4
        with:
          markdown: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "docs: synchronizing README.md"
          silent: true
