name: 'Unit test'

on:
  workflow_call:

jobs:
  unit-test:
    name: "/"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: technology-studio/github-workflows/.github/actions/install-dependencies@main
      - run: yarn test --coverage
      - id: check-dir
        run: |
          if [[ -d "coverage" ]]; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi
      - if: steps.check-dir.outputs.exists == 'true'
        uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574 # v5
      - name: Send a Slack message on failure
        if: failure()
        uses: technology-studio/github-workflows/.github/actions/slack-failed-job-message@main
        with:
          slack_bot_token: ${{ secrets.TXO_SLACK_BOT_APP_TOKEN }}
          channel_id: ${{ secrets.TXO_SLACK_GITHUB_OPS_CHANNEL_ID }}
