name: 'Unit test'

on:
  workflow_call:

jobs:
  unit-test:
    name: "/"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: technology-studio/github-workflows/.github/actions/install-dependencies@main
      - run: yarn test --coverage
      - id: check-dir
        run: |
          if [[ -d "coverage" ]]; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi
      - if: steps.check-dir.outputs.exists == 'true'
        id: codecov
        continue-on-error: true
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          fail_ci_if_error: true
      - name: Send a Slack message on codecov failure
        if: steps.codecov.outcome == 'failure'
        uses: technology-studio/github-workflows/.github/actions/slack-failed-job-message@main
        with:
          slack_bot_token: ${{ secrets.TXO_SLACK_BOT_APP_TOKEN }}
          channel_id: ${{ secrets.TXO_SLACK_GITHUB_OPS_CHANNEL_ID }}
          status_text: '🟠 codecov upload failed (job continued)'
      - name: Send a Slack message on failure
        if: failure()
        uses: technology-studio/github-workflows/.github/actions/slack-failed-job-message@main
        with:
          slack_bot_token: ${{ secrets.TXO_SLACK_BOT_APP_TOKEN }}
          channel_id: ${{ secrets.TXO_SLACK_GITHUB_OPS_CHANNEL_ID }}
