name: 'Unit test'

on:
  workflow_call:

jobs:
  unit-test:
    name: "/"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: technology-studio/github-workflows/.github/actions/install-dependencies@main
      - run: yarn test --coverage
      - id: check-dir
        run: |
          if [[ -d "coverage" ]]; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi
      - if: steps.check-dir.outputs.exists == 'true'
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5
      - name: Send a Slack message on failure
        if: failure()
        uses: technology-studio/github-workflows/.github/actions/slack-failed-job-message@main
        with:
          slack_bot_token: ${{ secrets.TXO_SLACK_BOT_APP_TOKEN }}
          channel_id: ${{ secrets.TXO_SLACK_GITHUB_OPS_CHANNEL_ID }}
