name: Deduplicate yarn.lock

on:
  workflow_call:
    secrets:
      TXO_GITHUB_BOT_APP_ID:
        required: true
      TXO_GITHUB_BOT_APP_PRIVATE_KEY:
        required: true

jobs:
  resolve-yarn-lock:
    name: "/"
    runs-on: ubuntu-latest
    steps:
      - uses: technology-studio/github-workflows/.github/actions/github-app-token-generator@main
        id: get-token
        with:
          app-id: ${{ secrets.TXO_GITHUB_BOT_APP_ID }}
          private-key: ${{ secrets.TXO_GITHUB_BOT_APP_PRIVATE_KEY }}
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          token: ${{ steps.get-token.outputs.token }}

      - name: Run `npx yarn-deduplicate`
        run: |
          npx yarn-deduplicate
          yarn

      - name: Commit yarn.lock
        run: |
          git config --global user.email "txo-github-bot[bot]@users.noreply.github.com"
          git config --global user.name "TXO GitHub Bot[bot]"
          git add yarn.lock
          git commit -m "chore: run \`npx yarn-deduplicate\`"

      - name: Push yarn.lock
        run: |
          git push
