name: Deduplicate yarn.lock

on:
  workflow_call:
    secrets:
      TXO_GITHUB_BOT_APP_ID:
        required: true
      TXO_GITHUB_BOT_APP_PRIVATE_KEY:
        required: true

jobs:
  resolve-yarn-lock:
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/github-app-token-generator@b96ff604b2300989cd1105e3fad09199fca56681 # v1
        id: get-token
        with:
          app-id: ${{ secrets.TXO_GITHUB_BOT_APP_ID }}
          private-key: ${{ secrets.TXO_GITHUB_BOT_APP_PRIVATE_KEY }}
      - name: Checkout code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
        with:
          token: ${{ steps.get-token.outputs.token }}

      - name: Run `npx yarn-deduplicate`
        run: |
          npx yarn-deduplicate
          yarn

      - name: Commit yarn.lock
        run: |
          git config --global user.email "txo-github-bot[bot]@users.noreply.github.com"
          git config --global user.name "TXO GitHub Bot[bot]"
          git add yarn.lock
          git commit -m "chore: run \`npx yarn-deduplicate\`"

      - name: Push yarn.lock
        run: |
          git push
